version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./:/app
  db:
    image: postgres:12.9
    environment:
      - POSTGRES_DB=node_example
      - POSTGRES_PASSWORD=teste
      - POSTGRES_USER=node_example_user
    volumes:
      - ./docker/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run worker
    volumes:
      - ./:/app

